# tasks file for install_jenkins
---
- name: Instalando pip docker, docker-compose
  pip:
    name: [ "docker", "docker-compose" ]

- name: Clone Repos Git
  become: false
  git:
    repo: git@github.com:WagnerCOliveira/jenkins.git
    dest: /tmp/
    force: yes

- name: Copy ".env" 
  copy:
    src: .env
    dest: /tmp/.env
    owner: ansible
    group: ansible
    mode: '0644'
  
- name: Subindo Containers
  docker_compose:
    project_src: /tmp/jenkins